name: "Build validation"

on:
  push:
    branches:
      - "main"
jobs:
  kotlin-build:
    name: "Kotlin Build validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19

      - name: Build
        run: |
          cd example && ./gradlew kotlin-example:build

  webflux-build:
    name: "Webflux Build validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19

      - name: Build
        run: |
          cd example && ./gradlew kotlin-example:build
  java-build:
    name: "Java build validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19

      - name: Java build validation
        run: |
          cd example && ./gradlew java-example:build
