name: "Build validation"

on:
  push:

jobs:
  kotlin-build:
    name: "Kotlin Build validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Build
        run: |
          cd example && ./gradlew kotlin-example:build

  webflux-build:
    name: "Webflux Build validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Build
        run: |
          cd example && ./gradlew kotlin-example:build
  java-build:
    name: "Java build validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Java build validation
        run: |
          cd example && ./gradlew java-example:build
