name: "Build validation"

on:
  push:
    branches:
      - "main"
jobs:
  test-run:
    name: "Build execution validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19

      - name: Build validation
        run: |
          cd example && ./gradlew build
